import type { RuntimeBundle, RuntimeEntity } from "../runtime";
import type { BackupManifest, DailyPlanRecord, Preferences, QuestionRun, SkillState } from "./types";

export type Route = "home" | "study" | "diagnostic" | "words" | "stats" | "settings";
const esc = (v: unknown) => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
export function shell(route: Route, body: string): string {
  const nav = [["home","今日"],["words","単語一覧"],["stats","進捗"],["settings","設定"]] as const;
  return `<header class="masthead"><a class="brand" href="#home"><span class="crest">R</span><span><b>RIKKYO UK</b><small>VOCABULARY STUDIO</small></span></a><span class="preview-pill">CORE 241</span></header><main>${body}</main><nav class="learner-nav">${nav.map(([r,l])=>`<a href="#${r}" class="${route===r?"active":""}">${l}</a>`).join("")}</nav><footer>立教英国学院 入試英語 · Adaptive Vocabulary</footer>`;
}
function stageLabel(s?: SkillState): string { if (!s) return "未学習"; return s.stage === "learning" ? "学習中" : s.stage === "relearning" ? "再学習" : s.stage === "provisional" ? "仮習得" : "復習"; }
export function homeView(input: { bundle: RuntimeBundle; plan: DailyPlanRecord; memory: SkillState[]; answeredToday: number; activeSeconds: number; diagnosticCompleted: boolean }): string {
  const now = Date.now(), due = input.memory.filter((x)=>Date.parse(x.dueAt)<=now).length, weak = new Set(input.memory.filter((x)=>x.wrong>x.correct).map((x)=>x.stableId)).size;
  const active = new Set(input.memory.map((x)=>x.stableId)).size, mastered = new Set(input.memory.filter((x)=>x.stage==="review"&&x.correct>=2&&x.correct>x.wrong).map((x)=>x.stableId)).size;
  const remainMin = Math.max(0, Math.ceil((input.plan.targetSeconds-input.activeSeconds)/60));
  return shell("home", `<section class="hero compact-hero"><div class="eyebrow">TODAY</div><h1>今日やること</h1><p class="lead">復習期限・苦手・重要度・新規導入を自動で調整します。</p><div class="today-card"><div><span class="label">TODAY PLAN</span><h2>${due} 復習 · ${weak} 苦手</h2><p>目安あと ${remainMin}分 · Core進捗 ${active}/241</p></div><button class="primary" id="start-study">今日の学習を始める</button></div><div class="gate-grid stats"><article><span>今日回答</span><strong>${input.answeredToday}</strong><p>回答済み</p></article><article><span>習得</span><strong>${mastered}</strong><p>review安定</p></article><article><span>新規上限</span><strong>${input.plan.introducedStableIds.length}/12</strong><p>1日あたり</p></article></div>${input.diagnosticCompleted?"":`<aside class="notice"><b>初回診断</b><p>最大24問で既知語を仮判定し、後日の確認問題で確定します。診断ミスはlapseには数えません。</p><button class="secondary" id="start-diagnostic">診断を始める</button></aside>`}<section class="info-strip"><b>Core ${input.bundle.core.length}/241</b><span>FSRS-6 · retention 0.90</span><span>短期再学習と長期復習を分離</span></section></section>`);
}
export function questionView(q: QuestionRun, entity: RuntimeEntity, index: number, total: number, mode: "study"|"diagnostic", feedback?: { rating: string; answer: string }): string {
  const choices = q.choices.length ? `<div class="rich-choices">${q.choices.map((c)=>`<button class="rich-choice" data-answer="${esc(c)}" ${feedback?"disabled":""}>${esc(c)}</button>`).join("")}</div>` : `<form id="input-answer" class="answer-form"><input id="answer-input" autocomplete="off" autocapitalize="off" placeholder="英語で入力" ${feedback?"disabled":""}/><button class="primary" ${feedback?"disabled":""}>答える</button></form>`;
  return shell(mode === "diagnostic" ? "diagnostic" : "study", `<section class="study-screen"><div class="study-meta"><span>${mode==="diagnostic"?"DIAGNOSTIC":"TODAY"} · ${index+1}/${total}</span><button class="text-button" id="stop-session">終了</button></div><article class="study-card"><div class="question-flags"><span>${q.skillKey === "meaningRecognition" ? "英 → 日" : "日 → 英"}</span><span>${esc(q.lane)}</span><span>${esc(entity.priority ?? "")}</span></div><h2>${esc(q.prompt)}</h2>${q.skillKey === "meaningRecognition"?`<button id="speak-word" class="speaker" type="button">🔊</button>`:""}<p class="study-instruction">${q.skillKey === "meaningRecognition"?"最も適切な意味を選んでください":"対応する英語を入力してください"}</p>${choices}${feedback?`<div class="feedback ${feedback.rating==="Again"?"ng":"ok"}"><b>${feedback.rating==="Again"?"もう一度":"OK"}</b><span>正答: ${esc(feedback.answer)}</span></div><button class="primary" id="next-question">次へ</button>`:""}</article></section>`);
}
export function wordsView(bundle: RuntimeBundle, memory: SkillState[], query = "", filter = "all"): string {
  const byId = new Map<string, SkillState[]>(); for (const s of memory) byId.set(s.stableId,[...(byId.get(s.stableId)??[]),s]);
  const q=query.trim().toLowerCase(); const rows=bundle.core.filter((e)=>!q||e.lemma.toLowerCase().includes(q)||(e.senses[0]?.glossJa??"").includes(q)).filter((e)=>{const states=byId.get(e.stableId)??[]; if(filter==="weak")return states.some((x)=>x.wrong>x.correct); if(filter==="unseen")return states.length===0; if(filter==="due")return states.some((x)=>Date.parse(x.dueAt)<=Date.now()); return true;});
  return shell("words", `<section class="page"><div class="eyebrow">CORE 241</div><h1>単語一覧</h1><div class="word-tools"><input id="word-search" value="${esc(query)}" placeholder="英語・日本語で検索"><select id="word-filter"><option value="all" ${filter==="all"?"selected":""}>すべて</option><option value="weak" ${filter==="weak"?"selected":""}>苦手</option><option value="due" ${filter==="due"?"selected":""}>復習期限</option><option value="unseen" ${filter==="unseen"?"selected":""}>未学習</option></select></div><div class="word-list">${rows.map((e)=>{const ss=byId.get(e.stableId)??[]; return `<article><div><b>${esc(e.lemma)}</b><span>${esc(e.pos)} · ${esc(e.priority??"")}</span></div><p>${esc(e.senses[0]?.glossJa??"")}</p><small>${ss.length?ss.map((x)=>`${x.skillKey}:${stageLabel(x)}`).join(" / "):"未学習"}</small></article>`}).join("")}</div></section>`);
}
export function statsView(bundle: RuntimeBundle, memory: SkillState[], events: Array<{ type?: string; at?: string; payload?: Record<string, unknown> }>): string {
  const review=memory.filter((x)=>x.stage==="review").length, learning=memory.filter((x)=>x.stage==="learning"||x.stage==="relearning").length, provisional=memory.filter((x)=>x.stage==="provisional").length, weak=new Set(memory.filter((x)=>x.wrong>x.correct).map((x)=>x.stableId)).size;
  const entities=new Set(memory.map((x)=>x.stableId)).size, attempts=events.filter((x)=>x.type==="AnswerCommitted"||x.type==="DiagnosticAnswer").length;
  return shell("stats", `<section class="page"><div class="eyebrow">PROGRESS</div><h1>学習の進捗</h1><div class="gate-grid stats"><article><span>Core進捗</span><strong>${entities}/241</strong><p>学習開始済み</p></article><article><span>Review skills</span><strong>${review}</strong><p>長期復習へ移行</p></article><article><span>苦手語</span><strong>${weak}</strong><p>誤答優勢</p></article></div><div class="status-card light"><div class="status-icon">✓</div><div><span class="label">MEMORY MODEL</span><h2>学習 ${learning} · 仮習得 ${provisional}</h2><p>総回答 ${attempts}。記憶状態は単語だけでなく skill 単位で管理します。</p></div></div><p class="muted-block">対象データ: ${bundle.manifest.dataVersion} / Core ${bundle.core.length}</p></section>`);
}
export function settingsView(prefs: Preferences, backups: BackupManifest[]): string {
  return shell("settings", `<section class="page"><div class="eyebrow">SETTINGS & RECOVERY</div><h1>設定</h1><form id="settings-form" class="settings-card"><label>1日の目安（分）<input id="daily-target" type="number" min="5" max="120" value="${Math.round(prefs.dailyTargetSeconds/60)}"></label><label>学習タイムゾーン<input id="time-zone" value="${esc(prefs.learningTimeZone)}"></label><label>試験日<input id="exam-date" type="date" value="${esc(prefs.examDate??"")}"></label><button class="primary">保存</button></form><section class="recovery-card"><h2>バックアップ・復元</h2><p>ブラウザ内Backup DBと外部Exportは別レイヤーです。Import/Restore/Resetは新しいstate generationとして復元します。</p><div class="button-row"><button class="secondary" id="export-data">Export</button><button class="secondary" id="browser-backup">Browser Backup</button><label class="file-button">Import<input id="import-data" type="file" accept="application/json"></label><button class="danger" id="reset-data">学習データをリセット</button></div><div class="backup-list">${backups.length?backups.map((b)=>`<div><span>${new Date(b.createdAt).toLocaleString("ja-JP")} · ${esc(b.purpose)}</span><button class="text-button restore-backup" data-id="${esc(b.snapshotId)}">復元</button></div>`).join(""):"<p>ブラウザバックアップはまだありません。</p>"}</div></section></section>`);
}
