import type { RuntimeBundle, RuntimeEntity } from "../runtime";
import type { BackupManifest, DailyPlanRecord, Preferences, QuestionRun, SkillState } from "./types";

export type Route = "home" | "study" | "diagnostic" | "words" | "stats" | "analysis" | "settings";
const esc = (v: unknown) => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const MODE_OPTIONS = [["recommended", "おすすめ学習"], ["exam", "実戦トレーニング"], ["foundation", "基礎重点"], ["core", "Core重点"], ["challenge", "Challenge重点"], ["unlearned", "未学習"], ["weak", "苦手"], ["review", "復習期限"], ["frequent", "頻出語"], ["random", "ランダム"]] as const;

export function shell(route: Route, body: string): string {
  const active = route === "study" || route === "diagnostic" ? "home" : route;
  const nav = [["home", "▶︎", "学習"], ["words", "≡", "一覧"], ["stats", "▥", "統計"], ["analysis", "⌕", "分析"], ["settings", "⚙︎", "設定"]] as const;
  return `<header class="app-topbar"><a href="#home" class="top-title"><span>立教英国学院</span><b>Vocabulary</b></a><span class="core-count">CORE 241</span></header><main>${body}</main><nav class="learner-nav" aria-label="メインナビゲーション">${nav.map(([r, icon, label]) => `<a href="#${r}" class="${active === r ? "active" : ""}"><i>${icon}</i><span>${label}</span></a>`).join("")}</nav>`;
}

function stageLabel(s?: SkillState): string {
  if (!s) return "未学習";
  return s.stage === "learning" ? "学習中" : s.stage === "relearning" ? "再学習" : s.stage === "provisional" ? "仮習得" : s.stage === "acquisitionCandidate" ? "導入待ち" : "復習";
}

export function homeView(input: { bundle: RuntimeBundle; plan: DailyPlanRecord; memory: SkillState[]; answeredToday: number; activeSeconds: number; diagnosticCompleted: boolean; preferences: Preferences }): string {
  const due = input.memory.filter((x) => Date.parse(x.dueAt) <= Date.now()).length;
  const weak = new Set(input.memory.filter((x) => x.wrong > x.correct).map((x) => x.stableId)).size;
  const active = new Set(input.memory.map((x) => x.stableId)).size;
  const mastered = new Set(input.memory.filter((x) => x.stage === "review" && x.correct >= 2 && x.correct > x.wrong).map((x) => x.stableId)).size;
  const remainMin = Math.max(0, Math.ceil((input.plan.targetSeconds - input.activeSeconds) / 60));
  const mode = input.preferences.studyMode ?? "recommended", size = input.preferences.sessionSize ?? 20;
  const audio = input.preferences.audioQuestions === "off" ? "音声問題なし" : "音声問題は利用環境に合わせて自動調整";
  return shell("home", `<section class="page home-page"><h1>学習</h1><section class="ios-card start-card"><h2>次に覚える語を自動選択</h2><p>復習期限・苦手度・立教過去問での頻度から、今やるべき語を組み立てます。A/B日程で出題は分けません。</p><div class="learn-controls"><label>学習モード<select id="study-mode">${MODE_OPTIONS.map(([v, l]) => `<option value="${v}" ${v === mode ? "selected" : ""}>${l}</option>`).join("")}</select></label><label>問題数<select id="session-size"><option value="10" ${size === 10 ? "selected" : ""}>10問</option><option value="20" ${size === 20 ? "selected" : ""}>20問</option><option value="30" ${size === 30 ? "selected" : ""}>30問</option><option value="50" ${size === 50 ? "selected" : ""}>50問</option><option value="0" ${size === 0 ? "selected" : ""}>できるだけ</option></select></label></div><button class="primary" id="start-study">学習を始める</button><div class="plan-line"><span>復習 ${due}</span><span>苦手 ${weak}</span><span>目安あと ${remainMin}分</span><span>${audio}</span></div></section>
  <h2 class="section-title">今日の進捗</h2><section class="mini-stats"><article><strong>${input.answeredToday}</strong><span>今日の回答</span></article><article><strong>${mastered}</strong><span>習得語</span></article><article><strong>${active}<small>/241</small></strong><span>学習済み</span></article></section>
  ${input.diagnosticCompleted ? "" : `<section class="ios-card notice"><div><h2>初回診断</h2><p>最大24問で既知語を仮判定します。診断の誤答は学習上のミスに数えません。</p></div><button class="secondary" id="start-diagnostic">診断を始める</button></section>`}
  <section class="ios-card design-card"><h2>立教入試に合わせた設計</h2><div class="feature-row"><span>7形式</span><p>意味・逆引き・英語入力・文脈穴埋め入力を習得度に合わせて出題</p></div><div class="feature-row"><span>6冊</span><p>FY24–FY26の英語A/Bを一体化し、頻度と出典例文を紐づけ</p></div><div class="feature-row"><span>実戦</span><p>入力・文脈中心の実戦トレーニングを選択可能</p></div><div class="feature-row"><span>FSRS</span><p>意味認識と語形産出を別々にスケジュール</p></div><small>Core ${input.bundle.core.length}/241 · 目標保持率 90%</small></section></section>`);
}

function exampleBlock(entity: RuntimeEntity): string {
  if (entity.sourceExample) { const ex = entity.sourceExample; return `<div class="exam-example"><b>過去問での出現　FY${String(ex.year).slice(-2)} ${esc(ex.schedule)} · PDF p.${ex.page}</b><p>${esc(ex.sentence)}</p><small>中心語義：${esc(entity.senses[0]?.glossJa ?? "")}</small></div>`; }
  if (entity.generatedExample) return `<div class="exam-example generated"><b>立教の出題傾向から生成した例文</b><p>${esc(entity.generatedExample.sentence)}</p><small>${esc(entity.generatedExample.ja)}</small></div>`;
  return "";
}

export function questionView(q: QuestionRun, entity: RuntimeEntity, index: number, total: number, mode: "study" | "diagnostic", score: { correct: number; wrong: number; baseTotal: number }, feedback?: { rating: string; answer: string; given: string }): string {
  const audio = q.kind === "audioChoice" || q.kind === "audioInput";
  const labels: Record<string, string> = { meaningChoice: "選択式・英→日", reverseChoice: "選択式・日→英", input: "日→英・入力", audioChoice: "音声→意味選択", audioInput: "音声→英語入力", clozeChoice: "文脈・選択", clozeInput: "文脈・入力" };
  const instruction = q.kind === "reverseChoice" ? "対応する英語を選んでください" : q.kind === "input" ? "対応する英語を入力してください" : q.kind === "audioChoice" ? "音声を聞いて意味を選んでください" : q.kind === "audioInput" ? "音声を聞いて英語を入力してください" : q.kind === "clozeChoice" ? "空所に入る語句を選んでください" : q.kind === "clozeInput" ? "空所に入る見出し語を英語で入力してください" : "最も適切な意味を選んでください";
  const choices = q.choices.length ? `<div class="rich-choices">${q.choices.map((c) => { const state = feedback ? c === q.answer ? "correct-choice" : c === feedback.given ? "wrong-choice" : "" : ""; return `<button class="rich-choice ${state}" data-answer="${esc(c)}" ${feedback ? "disabled" : ""}>${esc(c)}</button>`; }).join("")}</div>` : `<form id="input-answer" class="answer-form"><input id="answer-input" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="英語で入力" ${feedback ? "disabled" : ""}/><button class="primary" ${feedback ? "disabled" : ""}>答える</button></form>`;
  const title = audio ? `<button id="speak-word" class="audio-orb" type="button" aria-label="音声を聞く">🔊</button><button id="audio-fallback" class="text-button audio-fallback" type="button">音声が使えない場合</button>` : q.kind === "clozeChoice" || q.kind === "clozeInput" ? `<div class="cloze-prompt">${esc(q.context ?? "")}</div>` : `<h2>${esc(q.prompt)}</h2>${q.skillKey === "meaningRecognition" ? `<button id="speak-word" class="speaker" type="button" aria-label="発音を聞く">🔊</button>` : ""}`;
  return shell(mode === "diagnostic" ? "diagnostic" : "study", `<section class="study-screen"><div class="sessionbar"><div><b>${q.isRetry ? "再確認" : mode === "diagnostic" ? "診断" : `問題 ${Math.min(index + 1, score.baseTotal)} / ${score.baseTotal}`}</b><small>${index + 1}/${total}</small></div><div class="live-score"><span class="score-ok">✓ ${score.correct}</span><span class="score-ng">× ${score.wrong}</span><button class="text-button" id="stop-session">終了</button></div></div><article class="study-card"><div class="question-flags"><span>${esc(labels[q.kind ?? "meaningChoice"] ?? q.kind)}</span><span>${esc(q.lane)}</span><span>${esc(entity.priority ?? "")}</span>${q.sourceLabel ? `<span>${esc(q.sourceLabel)}</span>` : ""}</div>${title}<p class="study-instruction">${instruction}</p>${choices}${feedback ? `<div class="feedback ${feedback.rating === "Again" ? "ng" : "ok"}"><b>${feedback.rating === "Again" ? "もう一度確認" : "正解"}</b><span>正答：${esc(feedback.answer)}</span></div>${exampleBlock(entity)}<button class="primary next-button" id="next-question">次へ</button>` : ""}</article></section>`);
}

export function sessionResultView(input: { mode: "study" | "diagnostic"; baseTotal: number; correct: number; wrong: number; retryAnswered: number; missed: RuntimeEntity[] }): string {
  const rate = input.correct + input.wrong ? Math.round(input.correct / (input.correct + input.wrong) * 100) : 0;
  return shell(input.mode === "diagnostic" ? "diagnostic" : "study", `<section class="page result-page"><div class="result-mark">✓</div><h1>${input.mode === "diagnostic" ? "診断完了" : "学習完了"}</h1><p>おつかれさまでした。今回の結果を次の出題順に反映しました。</p><section class="mini-stats result-stats"><article><strong>${rate}%</strong><span>正答率</span></article><article><strong>${input.correct}</strong><span>正解</span></article><article><strong>${input.wrong}</strong><span>誤答</span></article></section>${input.retryAnswered ? `<p class="retry-note">誤答の再チャレンジ ${input.retryAnswered}問を実施しました。</p>` : ""}${input.missed.length ? `<section class="ios-card weak-list"><h2>今回確認したい語</h2>${input.missed.slice(0, 8).map((e) => `<div><b>${esc(e.lemma)}</b><span>${esc(e.senses[0]?.glossJa ?? "")}</span></div>`).join("")}</section>` : ""}<div class="result-actions"><button class="primary" id="result-home">学習画面へ</button><button class="secondary" id="result-retry">続けて学習</button></div></section>`);
}

export function wordsView(bundle: RuntimeBundle, memory: SkillState[], query = "", filter = "all"): string {
  const byId = new Map<string, SkillState[]>(); for (const s of memory) byId.set(s.stableId, [...(byId.get(s.stableId) ?? []), s]);
  const q = query.trim().toLowerCase();
  const rows = bundle.core.filter((e) => !q || e.lemma.toLowerCase().includes(q) || (e.senses[0]?.glossJa ?? "").includes(q)).filter((e) => { const states = byId.get(e.stableId) ?? []; if (filter === "weak") return states.some((x) => x.wrong > x.correct); if (filter === "unseen") return states.length === 0; if (filter === "due") return states.some((x) => Date.parse(x.dueAt) <= Date.now()); if (filter === "foundation") return e.targetBand === "Foundation"; if (filter === "core") return e.targetBand === "Core"; if (filter === "challenge") return e.targetBand === "Challenge"; if (filter === "frequent") return e.observedFrequency >= 3 || e.priority === "S"; if (/^FY/.test(filter)) return e.years.includes(Number(filter.slice(2))); return true; });
  return shell("words", `<section class="page"><h1>単語一覧</h1><p class="page-lead">入試水準へ再選定した241語から検索・絞り込みできます。</p><div class="word-tools"><input id="word-search" value="${esc(query)}" placeholder="英語・日本語で検索"><select id="word-filter"><option value="all" ${filter === "all" ? "selected" : ""}>すべて</option><optgroup label="学習状況"><option value="weak" ${filter === "weak" ? "selected" : ""}>苦手</option><option value="due" ${filter === "due" ? "selected" : ""}>復習期限</option><option value="unseen" ${filter === "unseen" ? "selected" : ""}>未学習</option></optgroup><optgroup label="出題層"><option value="foundation" ${filter === "foundation" ? "selected" : ""}>Foundation</option><option value="core" ${filter === "core" ? "selected" : ""}>Core</option><option value="challenge" ${filter === "challenge" ? "selected" : ""}>Challenge</option><option value="frequent" ${filter === "frequent" ? "selected" : ""}>頻出</option></optgroup><optgroup label="過去問年度"><option value="FY2024" ${filter === "FY2024" ? "selected" : ""}>FY24</option><option value="FY2025" ${filter === "FY2025" ? "selected" : ""}>FY25</option><option value="FY2026" ${filter === "FY2026" ? "selected" : ""}>FY26</option></optgroup></select></div><p class="result-count">${rows.length}語</p><div class="word-list">${rows.map((e) => { const ss = byId.get(e.stableId) ?? []; const source = e.years.length ? `FY${e.years.map((y) => String(y).slice(-2)).join("/")} · ${e.observedFrequency}回確認` : "立教傾向から生成"; return `<details><summary><div><b>${esc(e.lemma)}</b><span>${esc(e.priority)} · ${esc(e.targetBand)}</span></div><p>${esc(e.senses[0]?.glossJa ?? "")}</p><small>${ss.length ? ss.map((x) => stageLabel(x)).join(" / ") : "未学習"}</small></summary><div class="word-detail"><p><b>過去問根拠：</b>${esc(source)}</p><p><b>カテゴリー：</b>${esc(e.categories.join(" / ") || "補完データ")}</p>${exampleBlock(e)}</div></details>`; }).join("")}</div></section>`);
}

export function statsView(bundle: RuntimeBundle, memory: SkillState[], events: Array<{ type?: string; at?: string; payload?: Record<string, unknown> }>): string {
  const review = memory.filter((x) => x.stage === "review").length, learning = memory.filter((x) => x.stage === "learning" || x.stage === "relearning").length, provisional = memory.filter((x) => x.stage === "provisional").length;
  const weak = new Set(memory.filter((x) => x.wrong > x.correct).map((x) => x.stableId)).size, entities = new Set(memory.map((x) => x.stableId)).size;
  const attempts = events.filter((x) => x.type === "AnswerCommitted" || x.type === "DiagnosticAnswer").length;
  const stages = [{ label: "復習", value: review }, { label: "学習中", value: learning }, { label: "仮習得", value: provisional }, { label: "未学習", value: Math.max(0, bundle.core.length - entities) }];
  const bands = ["Foundation", "Core", "Challenge"].map((band) => { const all = bundle.core.filter((e) => e.targetBand === band); const ids = new Set(all.map((e) => e.stableId)); return { label: band, total: all.length, value: new Set(memory.filter((m) => ids.has(m.stableId)).map((m) => m.stableId)).size }; });
  return shell("stats", `<section class="page"><h1>学習統計</h1><section class="mini-stats"><article><strong>${entities}<small>/241</small></strong><span>学習済み</span></article><article><strong>${attempts}</strong><span>総回答</span></article><article><strong>${weak}</strong><span>苦手語</span></article></section><h2 class="section-title">学習層別の進捗</h2><section class="ios-card progress-card">${bands.map((x) => `<div class="progress-row"><div><b>${x.label}</b><span>${x.value}/${x.total}</span></div><progress max="${x.total}" value="${x.value}"></progress></div>`).join("")}</section><h2 class="section-title">習得ステータス</h2><section class="ios-card progress-card">${stages.map((x) => `<div class="progress-row"><div><b>${x.label}</b><span>${x.value}</span></div><progress max="${Math.max(1, bundle.core.length)}" value="${x.value}"></progress></div>`).join("")}</section><p class="footnote">意味認識と語形産出は別々に管理。FSRS-6 · 目標保持率 90% · ${bundle.manifest.dataVersion}</p></section>`);
}

export function analysisView(bundle: RuntimeBundle): string {
  const matched = bundle.core.filter((x) => x.evidence.length).length, examples = bundle.core.filter((x) => x.generatedExample).length;
  const byYear = [2024, 2025, 2026].map((year) => ({ label: `FY${String(year).slice(-2)}`, count: bundle.core.filter((x) => x.years.includes(year)).length }));
  const top = [...bundle.core].sort((a, b) => b.observedFrequency - a.observedFrequency || a.lemma.localeCompare(b.lemma)).slice(0, 100);
  return shell("analysis", `<section class="page"><h1>過去問分析</h1><p class="page-lead">FY24–FY26 英語6冊を日程で分けずに統合し、難易度・再出現・読解への影響で241語を再選定しています。</p><section class="mini-stats"><article><strong>6</strong><span>分析冊数</span></article><article><strong>${matched}</strong><span>出典照合語</span></article><article><strong>${examples}</strong><span>練習例文</span></article></section><div class="analysis-grid"><section class="ios-card"><h2>年度別</h2>${byYear.map((x) => `<div class="bar-row"><span>${x.label}</span><progress max="241" value="${x.count}"></progress><b>${x.count}</b></div>`).join("")}</section><section class="ios-card"><h2>再選定基準</h2><p>本文注釈語・共通指示文・定型文・初歩語を優先度計算から除外。学術・実用読解語と記述に使う語をCore／Challengeへ反映しました。</p></section></div><section class="ios-card top-table"><h2>確認回数 TOP 100</h2><div class="table-scroll"><table><thead><tr><th>語</th><th>意味</th><th>回数</th><th>年度</th><th>優先度</th></tr></thead><tbody>${top.map((e) => `<tr><td><b>${esc(e.lemma)}</b></td><td>${esc(e.senses[0]?.glossJa ?? "")}</td><td>${e.observedFrequency}</td><td>${esc(e.years.map((y) => `FY${String(y).slice(-2)}`).join("/"))}</td><td>${esc(e.priority)}</td></tr>`).join("")}</tbody></table></div></section><section class="ios-card method-note"><h2>データの扱い</h2><p>過去問との語形照合結果と、立教の出題傾向から作成した練習例文を区別して保持しています。音源・公式解答がない内容は推測で補完しません。</p></section></section>`);
}

export function settingsView(prefs: Preferences, backups: BackupManifest[]): string {
  const accent = prefs.accent ?? "auto", theme = prefs.theme ?? "auto", audioQuestions = prefs.audioQuestions ?? "auto";
  return shell("settings", `<section class="page"><h1>設定</h1><form id="settings-form"><section class="ios-card settings-card"><h2>学習</h2><label>1日の目安（分）<input id="daily-target" type="number" min="5" max="120" value="${Math.round(prefs.dailyTargetSeconds / 60)}"></label><label>学習タイムゾーン<input id="time-zone" value="${esc(prefs.learningTimeZone)}"></label><label>試験日<input id="exam-date" type="date" value="${esc(prefs.examDate ?? "")}"></label></section><section class="ios-card settings-card"><h2>音声</h2><label>音声問題<select id="audio-questions"><option value="auto" ${audioQuestions === "auto" ? "selected" : ""}>自動（利用不可なら除外）</option><option value="on" ${audioQuestions === "on" ? "selected" : ""}>使用する</option><option value="off" ${audioQuestions === "off" ? "selected" : ""}>使用しない</option></select></label><label>発音<select id="accent"><option value="auto" ${accent === "auto" ? "selected" : ""}>自動</option><option value="gb" ${accent === "gb" ? "selected" : ""}>イギリス英語</option><option value="us" ${accent === "us" ? "selected" : ""}>アメリカ英語</option></select></label><label>音声<select id="voice"><option value="">端末の標準音声</option></select></label><button class="secondary" id="voice-test" type="button">“vocabulary” を再生</button><p class="setting-note">音声が再生できない場合は、自動的に文字問題へ切り替わります。問題画面からも即時切替できます。</p></section><section class="ios-card settings-card"><h2>表示</h2><label>テーマ<select id="theme"><option value="auto" ${theme === "auto" ? "selected" : ""}>端末設定</option><option value="light" ${theme === "light" ? "selected" : ""}>ライト</option><option value="dark" ${theme === "dark" ? "selected" : ""}>ダーク</option></select></label></section><button class="primary save-settings">設定を保存</button></form><h2 class="section-title">データ管理</h2><section class="ios-card recovery-card"><p>端末内バックアップとJSON書き出しを併用できます。復元時も安定IDと学習履歴を保ちます。</p><div class="button-row"><button class="secondary" id="export-data">書き出す</button><button class="secondary" id="browser-backup">端末内バックアップ</button><label class="file-button">読み込む<input id="import-data" type="file" accept="application/json"></label></div><div class="backup-list">${backups.length ? backups.map((b) => `<div><span>${new Date(b.createdAt).toLocaleString("ja-JP")} · ${esc(b.purpose)}</span><button class="text-button restore-backup" data-id="${esc(b.snapshotId)}">復元</button></div>`).join("") : "<p>端末内バックアップはまだありません。</p>"}</div><button class="danger" id="reset-data">学習データをリセット</button></section><p class="footnote">立教英国学院 Vocabulary · Core 241 · 永続化スキーマ v3</p></section>`);
}
