import { SCHOOL } from "../school-config";
import type { RuntimeBundle, RuntimeEntity } from "../runtime";
import { questionCopy, resolveQuestionKind, sessionProgress } from "../common-engine/learning-ui";
import type { BackupManifest, DailyPlanRecord, Preferences, QuestionRun, SkillState } from "./types";

export type Route = "home" | "study" | "diagnostic" | "words" | "stats" | "analysis" | "settings";
const esc = (v: unknown) => String(v ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const MODE_OPTIONS = [["recommended", "おすすめ学習"], ["exam", "実戦トレーニング"], ["foundation", "基礎重点"], ["core", "Core重点"], ["challenge", "Challenge重点"], ["unlearned", "未学習"], ["weak", "苦手"], ["review", "復習期限"], ["frequent", "頻出語"], ["random", "ランダム"]] as const;

export function shell(route: Route, body: string, title = route === "home" ? "おすすめ学習" : route === "words" ? "単語一覧" : route === "stats" ? "学習統計" : route === "analysis" ? "過去問分析" : route === "settings" ? "設定" : "学習"): string {
  const active = route === "study" || route === "diagnostic" ? "home" : route;
  const nav = [["home", "▶︎", "学習"], ["words", "≡", "一覧"], ["stats", "▥", "統計"], ["analysis", "⌕", "分析"], ["settings", "⚙︎", "設定"]] as const;
  return `<header class="topbar"><div class="topbar-row"><div><div class="title">${esc(title)}</div><div class="subtitle">${esc(SCHOOL.subtitle)}</div></div><button class="icon-btn" id="quick-speak" aria-label="音声テスト">🔊</button></div></header><main>${body}</main><nav class="nav learner-nav" aria-label="メインナビゲーション"><div class="nav-inner">${nav.map(([r, icon, label]) => `<a href="#${r}" class="${active === r ? "active" : ""}" ${active === r ? 'aria-current="page"' : ""}><b>${icon}</b>${label}</a>`).join("")}</div></nav>`;
}

function stageLabel(s?: SkillState): string {
  if (!s) return "未学習";
  return s.stage === "learning" ? "学習中" : s.stage === "relearning" ? "再学習" : s.stage === "provisional" ? "仮習得" : s.stage === "acquisitionCandidate" ? "導入待ち" : "復習";
}

export function homeView(input: { bundle: RuntimeBundle; plan: DailyPlanRecord; memory: SkillState[]; answeredToday: number; activeSeconds: number; diagnosticCompleted: boolean; preferences: Preferences }): string {
  const due = new Set(input.memory.filter((x) => Date.parse(x.dueAt) <= Date.now()).map(x => x.stableId)).size;
  const weak = new Set(input.memory.filter((x) => x.wrong > x.correct).map((x) => x.stableId)).size;
  const active = new Set(input.memory.map((x) => x.stableId)).size;
  const mastered = new Set(input.memory.filter((x) => x.stage === "review" && x.correct >= 2 && x.correct > x.wrong).map((x) => x.stableId)).size;
  const mode = input.preferences.studyMode ?? "recommended", size = input.preferences.sessionSize ?? 20;
  const title = MODE_OPTIONS.find(([value]) => value === mode)?.[1] ?? "おすすめ学習";
  const stats = [[input.answeredToday, "今日の回答"], [mastered, "習得語"], [active, "学習済み"], [weak, "苦手語"]];
  return shell("home", `<section class="home-page"><h1 class="visually-hidden">学習</h1><section class="card start-card"><h2>次に覚える語を自動選択</h2><p class="small muted" style="margin-top:0">過去問実績 × 入試上の重要度 × 習熟度 × 復習期限で優先順位を決めます。</p><div class="field" style="margin-top:14px"><label for="study-mode">学習モード</label><select id="study-mode">${MODE_OPTIONS.map(([v, l]) => `<option value="${v}" ${v === mode ? "selected" : ""}>${l}</option>`).join("")}</select></div><div class="controls" style="margin-top:10px"><div class="field"><label>対象</label><div class="scope-label">全年度・全日程</div></div><div class="field"><label for="session-size">問題数</label><select id="session-size">${[10,20,30,50,0].map(n => `<option value="${n}" ${size === n ? "selected" : ""}>${n ? n + "問" : "できるだけ"}</option>`).join("")}</select></div></div><button class="primary full" id="start-study" style="margin-top:14px">学習を始める</button></section>
  <section class="card"><div class="row between"><h3>今日の進捗</h3><span class="tiny muted">復習期限 ${due}語</span></div><div class="grid">${stats.map(([n,l]) => `<div class="stat"><div class="n">${n}</div><div class="l">${l}</div></div>`).join("")}</div></section>
  <section class="card"><h3>学習の進め方</h3><p class="small muted">新しい語は4択から始め、入力・文脈・音声の問題へ進みます。間違えた語は間隔を空けて1回再確認します。間隔を確保できない場合は次回の復習へ回します。</p><p class="small muted">おすすめ学習は全レベルが対象です。正解した語は翌日以降、間違えた語は10分後以降に復習できます。</p><div class="tiny muted">${esc(SCHOOL.corpusLabel)} · ${input.bundle.core.length}語</div></section>
  ${input.diagnosticCompleted ? "" : `<section class="card"><h3>初回診断</h3><p class="small muted">最大24問で既知語を確認します。診断の誤答は学習上のミスに数えません。</p><button class="secondary full" id="start-diagnostic">診断を始める</button></section>`}</section>`, title);
}

function exampleBlock(entity: RuntimeEntity): string {
  if (entity.sourceExample) { const ex = entity.sourceExample; return `<div class="exam-example"><b>過去問での出現　FY${String(ex.year).slice(-2)} ${esc(ex.schedule)} · PDF p.${ex.page}</b><p>${esc(ex.sentence)}</p><small>中心語義：${esc(entity.senses[0]?.glossJa ?? "")}</small></div>`; }
  if (entity.generatedExample) return `<div class="exam-example generated"><b>立教の出題傾向から生成した例文</b><p>${esc(entity.generatedExample.sentence)}</p><small>${esc(entity.generatedExample.ja)}</small></div>`;
  return "";
}

export function questionView(q: QuestionRun, entity: RuntimeEntity, mode: "study" | "diagnostic", score: { correct: number; wrong: number; basePosition: number; baseAnswered: number; baseTotal: number; retryAnswered: number; isLast?: boolean }, feedback?: { rating: string; answer: string; given: string }): string {
  const kind = resolveQuestionKind(q.kind, q.choices.length, q.skillKey);
  const audio = kind === "audioChoice" || kind === "audioInput";
  const copy = questionCopy(kind);
  const progress = sessionProgress({ mode, isRetry: q.isRetry === true, basePosition: score.basePosition, baseAnswered: score.baseAnswered, baseTotal: score.baseTotal, retryAnswered: score.retryAnswered, answeredCurrent: feedback !== undefined });
  const choices = q.choices.length ? `<div class="answer-grid rich-choices">${q.choices.map((c) => { const state = feedback ? c === q.answer ? "correct correct-choice" : c === feedback.given ? "wrong wrong-choice" : "" : ""; return `<button class="answer-btn rich-choice ${state}" data-answer="${esc(c)}" ${feedback ? "disabled" : ""}>${esc(c)}</button>`; }).join("")}</div>` : `<form id="input-answer" class="typebox answer-form"><input id="answer-input" type="text" aria-label="英語の回答" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="英語で入力" ${feedback ? "disabled" : ""}/><button class="primary" ${feedback ? "disabled" : ""}>答える</button></form>`;
  const title = audio ? `<button id="speak-word" class="audio-orb" type="button" aria-label="音声を聞く">🔊</button><button id="audio-fallback" class="text-button audio-fallback" type="button">音声が使えない場合</button>` : kind === "clozeChoice" || kind === "clozeInput" ? `<div class="cloze cloze-prompt">${esc(q.context ?? "")}</div>${kind === "clozeInput" ? `<p class="cloze-hint">意味：${esc(entity.senses[0]?.glossJa ?? "")}</p>` : ""}` : `<div class="${q.skillKey === "meaningRecognition" ? "word" : "meaning-big"}">${esc(q.prompt)}</div>${q.skillKey === "meaningRecognition" ? `<button id="speak-word" class="speaker" type="button" aria-label="発音を聞く">🔊</button>` : ""}`;
  const laneLabels: Record<string, string> = { acquisition: "新出", learning: "学習中", relearning: "再学習", provisional: "仮習得", review: "復習" };
  return shell(mode === "diagnostic" ? "diagnostic" : "study", `<section class="study-screen"><div class="sessionbar show row between"><div class="small"><b>${esc(progress.primary)}</b><small class="muted">${esc(progress.secondary)}</small><span class="muted">正解 ${score.correct} / 不正解 ${score.wrong}</span></div><button class="pill-btn" id="stop-session">終了</button></div><article class="card learn-card study-card"><div><div class="qmeta"><span>${esc(copy.label)}${q.isRetry ? "・再確認" : ""} ・ ${esc(laneLabels[q.lane] ?? q.lane)}</span><div class="badges"><span class="badge ${esc(entity.priority?.toLowerCase())}">${esc(entity.priority)}</span><span class="badge">${esc(entity.targetBand)}</span></div></div><div class="prompt">${title}<p class="small muted study-instruction">${esc(copy.instruction)}</p></div>${choices}</div>${feedback ? `<div class="feedback show ${feedback.rating === "Again" ? "ng" : "ok"}" role="status"><div class="correctline">${feedback.rating === "Again" ? "もう一度確認" : "正解"}</div><span>正答：${esc(feedback.answer)}</span><p class="small">${esc(entity.lemma)} — ${esc(entity.senses[0]?.glossJa ?? "")}</p>${exampleBlock(entity)}</div><button class="primary full next-button" id="next-question">${score.isLast ? "結果を見る" : "次へ"}</button>` : ""}</article></section>`);

}

export function sessionResultView(input: { mode: "study" | "diagnostic"; baseTotal: number; correct: number; wrong: number; retryAnswered: number; missed: RuntimeEntity[] }): string {
  const rate = input.correct + input.wrong ? Math.round(input.correct / (input.correct + input.wrong) * 100) : 0;
  const metrics = [[input.baseTotal, "基本問題"], [input.retryAnswered, "再確認"], [input.correct + input.wrong, "総回答"], [input.correct, "正解"], [input.wrong, "不正解"], [rate + "%", "正解率"]];
  return `<div class="overlay show"><section class="sheet result-page" role="dialog" aria-modal="true" aria-labelledby="result-title"><div class="sheet-handle"></div><h2 id="result-title">${input.mode === "diagnostic" ? "診断完了" : "セッション結果"}</h2><div class="grid">${metrics.map(([n,l]) => `<div class="stat"><div class="n">${n}</div><div class="l">${l}</div></div>`).join("")}</div><div class="section-title">今回ミスした語</div><div class="small">${input.missed.length ? input.missed.slice(0,18).map(e => esc(e.lemma)).join("・") : "なし"}</div><p class="small muted">今回の結果を次の出題順に反映しました。</p><div class="result-actions"><button class="primary" id="result-home">閉じる</button><button class="secondary" id="result-retry">続けて学習</button></div></section></div>`;
}

export function wordsView(bundle: RuntimeBundle, memory: SkillState[], query = "", filter = "all"): string {
  const byId = new Map<string, SkillState[]>(); for (const s of memory) byId.set(s.stableId, [...(byId.get(s.stableId) ?? []), s]);
  const q = query.trim().toLowerCase();
  const rows = bundle.core.filter((e) => !q || e.lemma.toLowerCase().includes(q) || (e.senses[0]?.glossJa ?? "").includes(q)).filter((e) => { const states = byId.get(e.stableId) ?? []; if (filter === "weak") return states.some((x) => x.wrong > x.correct); if (filter === "unseen") return states.length === 0; if (filter === "due") return states.some((x) => Date.parse(x.dueAt) <= Date.now()); if (filter === "foundation") return e.targetBand === "Foundation"; if (filter === "core") return e.targetBand === "Core"; if (filter === "challenge") return e.targetBand === "Challenge"; if (filter === "frequent") return e.observedFrequency >= 3 || e.priority === "S"; if (/^FY/.test(filter)) return e.years.includes(Number(filter.slice(2))); return true; });
  return shell("words", `<section class="page"><h1>単語一覧</h1><p class="page-lead">入試水準へ再選定した241語から検索・絞り込みできます。</p><div class="word-tools"><input id="word-search" value="${esc(query)}" placeholder="英語・日本語で検索"><select id="word-filter"><option value="all" ${filter === "all" ? "selected" : ""}>すべて</option><optgroup label="学習状況"><option value="weak" ${filter === "weak" ? "selected" : ""}>苦手</option><option value="due" ${filter === "due" ? "selected" : ""}>復習期限</option><option value="unseen" ${filter === "unseen" ? "selected" : ""}>未学習</option></optgroup><optgroup label="出題層"><option value="foundation" ${filter === "foundation" ? "selected" : ""}>Foundation</option><option value="core" ${filter === "core" ? "selected" : ""}>Core</option><option value="challenge" ${filter === "challenge" ? "selected" : ""}>Challenge</option><option value="frequent" ${filter === "frequent" ? "selected" : ""}>頻出</option></optgroup><optgroup label="過去問年度"><option value="FY2024" ${filter === "FY2024" ? "selected" : ""}>FY24</option><option value="FY2025" ${filter === "FY2025" ? "selected" : ""}>FY25</option><option value="FY2026" ${filter === "FY2026" ? "selected" : ""}>FY26</option></optgroup></select></div><p class="result-count">${rows.length}語</p><div class="word-list">${rows.map((e) => { const ss = byId.get(e.stableId) ?? []; const source = e.years.length ? `FY${e.years.map((y) => String(y).slice(-2)).join("/")} · ${e.observedFrequency}回確認` : "立教傾向から生成"; return `<details><summary><div><b>${esc(e.lemma)}</b><span>${esc(e.priority)} · ${esc(e.targetBand)}</span></div><p>${esc(e.senses[0]?.glossJa ?? "")}</p><small>${ss.length ? ss.map((x) => stageLabel(x)).join(" / ") : "未学習"}</small></summary><div class="word-detail"><p><b>過去問根拠：</b>${esc(source)}</p><p><b>カテゴリー：</b>${esc(e.categories.join(" / ") || "補完データ")}</p>${exampleBlock(e)}</div></details>`; }).join("")}</div></section>`);
}

export function statsView(bundle: RuntimeBundle, memory: SkillState[], events: Array<{ type?: string; at?: string; payload?: Record<string, unknown> }>): string {
  const review = memory.filter((x) => x.stage === "review").length, learning = memory.filter((x) => x.stage === "learning" || x.stage === "relearning").length, provisional = memory.filter((x) => x.stage === "provisional").length;
  const weak = new Set(memory.filter((x) => x.wrong > x.correct).map((x) => x.stableId)).size, entities = new Set(memory.map((x) => x.stableId)).size;
  const attempts = events.filter((x) => x.type === "AnswerCommitted" || x.type === "DiagnosticAnswer").length;
  const stages = [{ label: "復習", value: review }, { label: "学習中", value: learning }, { label: "仮習得", value: provisional }, { label: "未学習", value: Math.max(0, bundle.core.length - entities) }];
  const bands = ["Foundation", "Core", "Challenge"].map((band) => { const all = bundle.core.filter((e) => e.targetBand === band); const ids = new Set(all.map((e) => e.stableId)); return { label: band, total: all.length, value: new Set(memory.filter((m) => ids.has(m.stableId)).map((m) => m.stableId)).size }; });
  return shell("stats", `<section class="page"><h1>学習統計</h1><section class="mini-stats"><article><strong>${entities}<small>/241</small></strong><span>学習済み</span></article><article><strong>${attempts}</strong><span>総回答</span></article><article><strong>${weak}</strong><span>苦手語</span></article></section><h2 class="section-title">学習層別の進捗</h2><section class="card ios-card progress-card">${bands.map((x) => `<div class="progress-row"><div><b>${x.label}</b><span>${x.value}/${x.total}</span></div><progress max="${x.total}" value="${x.value}"></progress></div>`).join("")}</section><h2 class="section-title">習得ステータス</h2><section class="card ios-card progress-card">${stages.map((x) => `<div class="progress-row"><div><b>${x.label}</b><span>${x.value}</span></div><progress max="${Math.max(1, bundle.core.length)}" value="${x.value}"></progress></div>`).join("")}</section><p class="footnote">意味認識と語形産出は別々に管理。FSRS-6 · 目標保持率 90% · ${bundle.manifest.dataVersion}</p></section>`);
}

export function analysisView(bundle: RuntimeBundle): string {
  const matched = bundle.core.filter((x) => x.evidence.length).length, examples = bundle.core.filter((x) => x.generatedExample).length;
  const byYear = [2024, 2025, 2026].map((year) => ({ label: `FY${String(year).slice(-2)}`, count: bundle.core.filter((x) => x.years.includes(year)).length }));
  const top = [...bundle.core].sort((a, b) => b.observedFrequency - a.observedFrequency || a.lemma.localeCompare(b.lemma)).slice(0, 100);
  return shell("analysis", `<section class="page"><h1>過去問分析</h1><p class="page-lead">FY24–FY26 英語6冊を日程で分けずに統合し、難易度・再出現・読解への影響で241語を再選定しています。</p><section class="mini-stats"><article><strong>6</strong><span>分析冊数</span></article><article><strong>${matched}</strong><span>出典照合語</span></article><article><strong>${examples}</strong><span>練習例文</span></article></section><div class="analysis-grid"><section class="card ios-card"><h2>年度別</h2>${byYear.map((x) => `<div class="bar-row"><span>${x.label}</span><progress max="241" value="${x.count}"></progress><b>${x.count}</b></div>`).join("")}</section><section class="card ios-card"><h2>再選定基準</h2><p>本文注釈語・共通指示文・定型文・初歩語を優先度計算から除外。学術・実用読解語と記述に使う語をCore／Challengeへ反映しました。</p></section></div><section class="card ios-card top-table"><h2>確認回数 TOP 100</h2><div class="table-scroll"><table><thead><tr><th>語</th><th>意味</th><th>回数</th><th>年度</th><th>優先度</th></tr></thead><tbody>${top.map((e) => `<tr><td><b>${esc(e.lemma)}</b></td><td>${esc(e.senses[0]?.glossJa ?? "")}</td><td>${e.observedFrequency}</td><td>${esc(e.years.map((y) => `FY${String(y).slice(-2)}`).join("/"))}</td><td>${esc(e.priority)}</td></tr>`).join("")}</tbody></table></div></section><section class="card ios-card method-note"><h2>データの扱い</h2><p>過去問との語形照合結果と、立教の出題傾向から作成した練習例文を区別して保持しています。音源・公式解答がない内容は推測で補完しません。</p></section></section>`);
}

export function settingsView(prefs: Preferences, backups: BackupManifest[]): string {
  const accent = prefs.accent ?? "auto", theme = prefs.theme ?? "auto", audioQuestions = prefs.audioQuestions ?? "auto";
  return shell("settings", `<section class="page"><h1>設定</h1><form id="settings-form"><section class="card ios-card settings-card"><h2>学習</h2><label>1日の目安（分）<input id="daily-target" type="number" min="5" max="120" value="${Math.round(prefs.dailyTargetSeconds / 60)}"></label><label>学習タイムゾーン<input id="time-zone" value="${esc(prefs.learningTimeZone)}"></label><label>試験日<input id="exam-date" type="date" value="${esc(prefs.examDate ?? "")}"></label></section><section class="card ios-card settings-card"><h2>音声</h2><label>音声問題<select id="audio-questions"><option value="auto" ${audioQuestions === "auto" ? "selected" : ""}>自動（利用不可なら除外）</option><option value="on" ${audioQuestions === "on" ? "selected" : ""}>使用する</option><option value="off" ${audioQuestions === "off" ? "selected" : ""}>使用しない</option></select></label><label>発音<select id="accent"><option value="auto" ${accent === "auto" ? "selected" : ""}>自動</option><option value="gb" ${accent === "gb" ? "selected" : ""}>イギリス英語</option><option value="us" ${accent === "us" ? "selected" : ""}>アメリカ英語</option></select></label><label>音声<select id="voice"><option value="">端末の標準音声</option></select></label><button class="secondary" id="voice-test" type="button">“vocabulary” を再生</button><p class="setting-note">音声が再生できない場合は、自動的に文字問題へ切り替わります。問題画面からも即時切替できます。</p></section><section class="card ios-card settings-card"><h2>表示</h2><label>テーマ<select id="theme"><option value="auto" ${theme === "auto" ? "selected" : ""}>端末設定</option><option value="light" ${theme === "light" ? "selected" : ""}>ライト</option><option value="dark" ${theme === "dark" ? "selected" : ""}>ダーク</option></select></label></section><button class="primary save-settings">設定を保存</button></form><h2 class="section-title">データ管理</h2><section class="card ios-card recovery-card"><p>端末内バックアップとJSON書き出しを併用できます。復元時も安定IDと学習履歴を保ちます。</p><div class="button-row"><button class="secondary" id="export-data">書き出す</button><button class="secondary" id="browser-backup">端末内バックアップ</button><label class="file-button">読み込む<input id="import-data" type="file" accept="application/json"></label></div><div class="backup-list">${backups.length ? backups.map((b) => `<div><span>${new Date(b.createdAt).toLocaleString("ja-JP")} · ${esc(b.purpose)}</span><button class="text-button restore-backup" data-id="${esc(b.snapshotId)}">復元</button></div>`).join("") : "<p>端末内バックアップはまだありません。</p>"}</div><button class="danger" id="reset-data">学習データをリセット</button></section><p class="footnote">立教英国学院 Vocabulary · Core 241 · 永続化スキーマ v3</p></section>`);
}
